### ISSUE TITLE
[Bug] Pointer being freed was not allocated

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/credentialfs#10]
When a mounted credential has `permitDuration` long enough (say 10 minutes), we can observe crash with error message saying:

```
credentialfs(5090,0x7000070f8000) malloc: *** error for object 0x4b032b0: pointer being freed was not allocated
credentialfs(5090,0x7000070f8000) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff70f4e2c2 m=8 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff70f4e2c2
stack: frame={sp:0x7000070f7c08, fp:0x0} stack=[0x7000070782a0,0x7000070f7ea0)

// ....

goroutine 1 [syscall]:
runtime.cgocall(0x44e8f70, 0xc00005d918, 0x5d918)
        runtime/cgocall.go:154 +0x5b fp=0xc00005d8e8 sp=0xc00005d8b0 pc=0x400481b
arhat.dev/credentialfs/pkg/auth._Cfunc_destroy_auth(0x4e190e0, 0x0)
        _cgo_gotypes.go:102 +0x45 fp=0xc00005d918 sp=0xc00005d8e8 pc=0x4398ec5
arhat.dev/credentialfs/pkg/auth.DestroyAuthorization.func1(0x4e190e0, 0xc000000000)
        arhat.dev/credentialfs/pkg/auth/auth_darwin.go:68 +0x4d fp=0xc00005d948 sp=0xc00005d918 pc=0x439950d
arhat.dev/credentialfs/pkg/auth.DestroyAuthorization(0x451f040, 0x4e190e0, 0x0, 0x0)
        arhat.dev/credentialfs/pkg/auth/auth_darwin.go:68 +0x4f fp=0xc00005d9a0 sp=0xc00005d948 pc=0x43992af
arhat.dev/credentialfs/pkg/fs.(*authManager).Stop.func1(0xc00005dab8)
        arhat.dev/credentialfs/pkg/fs/auth_manager.go:100 +0x74 fp=0xc00005da00 sp=0xc00005d9a0 pc=0x43c81d4
arhat.dev/credentialfs/pkg/fs.(*authManager).Stop(0xc000072100, 0x0, 0x0)
        arhat.dev/credentialfs/pkg/fs/auth_manager.go:149 +0x348 fp=0xc00005daf0 sp=0xc00005da00 pc=0x43c3888
arhat.dev/credentialfs/pkg/fs.(*filesystem).Stop(0xc000074120, 0x0, 0x0)
        arhat.dev/credentialfs/pkg/fs/fs_unix.go:138 +0xa7 fp=0xc00005db88 sp=0xc00005daf0 pc=0x43c45e7
arhat.dev/credentialfs/pkg/fs.(*Manager).Stop(0xc0000a6000, 0x0, 0x0)
        arhat.dev/credentialfs/pkg/fs/manager.go:144 +0x86 fp=0xc00005dbc8 sp=0xc00005db88 pc=0x43c7c46
arhat.dev/credentialfs/pkg/cmd.run.func1(0xc0000a6000)
        arhat.dev/credentialfs/pkg/cmd/credentialfs.go:88 +0x2f fp=0xc00005dc28 sp=0xc00005dbc8 pc=0x44e82af
arhat.dev/credentialfs/pkg/cmd.run(0x4699ab8, 0xc00015eac0, 0xc000138420, 0x0, 0x0)
        arhat.dev/credentialfs/pkg/cmd/credentialfs.go:96 +0x2a9 fp=0xc00005dd10 sp=0xc00005dc28 pc=0x44e80a9
arhat.dev/credentialfs/pkg/cmd.NewRootCmd.func2(0xc000140f00, 0xc000158300, 0x0, 0x2, 0x0, 0x0)
        arhat.dev/credentialfs/pkg/cmd/credentialfs.go:60 +0x3f fp=0xc00005dd48 sp=0xc00005dd10 pc=0x44e823f
github.com/spf13/cobra.(*Command).execute(0xc000140f00, 0xc00011c190, 0x2, 0x2, 0xc000140f00, 0xc00011c190)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472 fp=0xc00005de08 sp=0xc00005dd48 pc=0x4325af2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000140f00, 0xc000193f50, 0x1, 0x1)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375 fp=0xc00005dee8 sp=0xc00005de08 pc=0x4326675
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        arhat.dev/credentialfs/cmd/credentialfs/main.go:35 +0xf4 fp=0xc00005df88 sp=0xc00005dee8 pc=0x44e8d94
runtime.main()
        runtime/proc.go:225 +0x256 fp=0xc00005dfe0 sp=0xc00005df88 pc=0x4039a96
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x406d841
```

Which suggests our destroy authorization process is some what not working when we have pointer reference to somewhere not managed by us (in this case, managed by the macos security service).

**Comment by jeffreystoke** [comment]
This was actually caused by wrong `continue` statement in auth manager `Stop()`, fixed with `break`
